apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- repo: https://openebs.github.io/openebs
  name: openebs
  namespace: openebs
  releaseName: openebs
  version: 4.4.0
  valuesFile: values.yaml

resources:
- storage-class.yaml
- volumes.yaml
